preset: PSR12
risky: true
enabled:
  - not_operator_with_successor_space
  - blank_line_before_return
  - simplified_null_return
  - single_blank_line_at_eof
finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
  name: "*.php"
  not-name: "*.blade.php"
