dist: xenial
language: php

php:
  - 7.4

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer update

script:
  - vendor/bin/psalm --shepherd
  - phpdbg -qrr vendor/bin/phpunit --testdox --coverage-clover clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls --json_path="coveralls.json"
