#!/usr/bin/env php
<?php declare(strict_types=1);

require_once "vendor/autoload.php";

use NotSoSimple\Commands\InitCommand;
use NotSoSimple\Commands\ScanCommand;
use NotSoSimple\Config;
use Symfony\Component\Console\Application;

$application = new Application('(Not So) Simple', Config::VERSION);
$application->setCatchExceptions(true);

$application->add($scan = new ScanCommand());
$application->add(new InitCommand());

$application->setDefaultCommand($scan->getName() ?? '');
$application->run();
