#!/usr/bin/env php
<?php declare(strict_types=1);

require_once "vendor/autoload.php";

use NotSoSimple\ScanCommand;
use Symfony\Component\Console\Application;

$application = new Application('simple', '1.0.0');
$command = new ScanCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();
